function fold(){$(".head-list").toggleClass("unfold")}function showChildren(a){$(a).parents(".item").toggleClass("active").siblings(".item").not(".not").removeClass("active")}function showFd(a){$(a).parents(".children").toggleClass("show")}
function setCollection(a){a=$(a);var b=0<a.parents("li").length?a.parents("li"):a.parents(".item"),c=b.data("id"),e=$(".competitions-"+c).find(".icon-collecth"),d=$(".prompt"),f=$(".fd-list.collection"),g=f.find("li:not(.prompt)").length;a.hasClass("active")?(e.removeClass("active animate"),f.find(".competitions-"+c).slideUp(100,function(){$(this).remove()}),1<g?d.addClass("hide"):d.removeClass("hide")):(e.addClass("active animate"),b.clone().appendTo(f),0<=g?d.addClass("hide"):d.removeClass("hide"),
setTimeout(function(){e.removeClass("animate")},700))}function DetailMatch(a){a=$(a);var b=a.data("round");a.addClass("active").siblings(".link,li").removeClass("active");$(".matches tr.data").each(function(){$(this).data("round")===b?$(this).removeClass("hide"):$(this).addClass("hide")})}
function ScreenMatch(a){a=$(a);var b=a.data("screen");a.addClass("active").siblings(".link,li").removeClass("active");$(".matches tr.data").each(function(){$(this).data("screen")===b?$(this).removeClass("hide"):$(this).addClass("hide")})}
function XScreenMatch(a){a=$(a);var b=a.data("screen");a.addClass("active").siblings(".link,li").removeClass("active");$('.groupttl, .league-match-screen, .matches, .jifen').each(function(){$(this).data("screen")===b?$(this).removeClass("hide"):$(this).addClass("hide")})}
function ScreenDetail(a){a=$(a);var b=a.data("round"),c=a.data("screen");a.addClass("active").siblings(".link,li").removeClass("active");$(".matches tr.data").each(function(){$(this).data("screen")===c?$(this).data("round")===b?$(this).removeClass("hide"):$(this).addClass("hide"):null})}
function GroupDetail(a){a=$(a);var b=a.data("group"),c=a.data("screen");a.addClass("active").siblings(".link,li").removeClass("active");$(".matches tr.data, .jifen tr.data").each(function(){$(this).data("screen")===c?$(this).data("group")===b?$(this).removeClass("hide"):$(this).addClass("hide"):null});$(".groupttl").each(function(){$(this).data("screen")===c?$(this).find("span").text(b):null})}
function tableListTdHover(){$(".table-list").find(".table-one:not(.matches), .table-tow:not(.matches)").find("tr:not(.tips, .incident, .no-haver) td").each(function(){var a=$(this),b=a.index(),c=!1;a.stop().hover(function(){c||(c=a.parents("tr").siblings("tr").find("td:nth-child("+(b+1)+")"));c.addClass("on")},function(){c&&c.removeClass("on")})})}
function toggleTableList(a){a=$(a);var b=a.data("id"),c=$(".match-nav-list .link-"+b),e=$(".select-"+b);b=$("#"+b);var d=$("#"+a.data("go"));a.addClass("active").siblings(".link").removeClass("active");c.addClass("active").siblings(".link").removeClass("active");a.siblings(".select-box").addClass("hide");c.siblings(".select-box").addClass("hide");e.removeClass("hide");b.removeClass("hide").siblings(".children.page-children").addClass("hide");d.length&&$("html, body").animate({scrollTop:d.offset().top-
44},1E3)}function shooter(a){a=$(a);var b=a.data("id");b=a.parents(".children.page-children").find(".table-page."+b);a.addClass("active").siblings(".link").removeClass("active");b.removeClass("hide").siblings(".table-page").addClass("hide")}$("document").ready(function(){(function(a,b){$(a).click(function(){$(this).addClass("active").siblings(b).removeClass("active")})})(".database .data-type-check .link",".link")});