function subscription(e){var $elem=e;var $child=e.childNodes[0];$($elem).hasClass("active")?($("#inform").addClass("d-none"),$($child).replaceWith("订阅")):($("#inform").removeClass("d-none"),$($child).replaceWith("已订阅"))}
function viewreply(e){var $elem=e;var $parent=$($elem).parent().parent();var $child=e.childNodes[0];var $child1=e.childNodes[1];$($elem).toggleClass('off');$($elem).hasClass("off")?($($child).replaceWith("隐藏"),$($child1).addClass("d-none")):($($child).replaceWith("查看全部"),$($child1).removeClass("d-none"))
$parent.find(".loaded-replies").toggleClass("d-none")}
function showtxtarea1(e){var $elem=e;var $parent=$($elem).parent().parent();var $replybox=$($parent).find(".replybox").first();var $txtbox=$($parent).find(".replybox>textarea").first();$($replybox).removeClass("d-none");$($txtbox).focus()}
function showtxtarea2(e){var $elem=e;var $parent=$($elem).parent().parent();var $replybox=$($parent).find(".replybox");var $txtbox=$($parent).find(".replybox>textarea");$($replybox).removeClass("d-none");$($txtbox).focus()}
function imputempty(e){var empty=!1;var $elem=e;var $parent=$($elem).parent();if($($elem).val().length==0){empty=!0}
if(empty){$($parent).find(".submit").attr("disabled","disabled")}else{$($parent).find(".submit").removeAttr("disabled")}}
function loadprogramlist(){$("#tvprograms").removeClass("d-none");$("#programlist").addClass("is-show");$("#program-btn").addClass("active");$("#tvprograms .epg-content.nano").nanoScroller({scrollTo:$(".epg-item.active")});$("#tvprograms .epg-header .selector .dropdown-menu").nanoScroller({scrollTo:$(".dropdown-item.active")});$("#closeprogram").click(function(){$("#tvprograms").addClass("d-none");$("#programlist").removeClass("is-show");$("#program-btn").removeClass("active")})}
function setsize(){if($('#superadv').length>0){$("#superadv").removeAttr("width left margin-left");var oWidth=pad_width;$("#superadv").css("left","50%");$("#superadv").css("margin-left",-oWidth/2)}}
function detectmode(){if($("body").hasClass("playmode2")){$("#tvprograms").addClass("d-none");if(!isMobile.any()){$("#superadv").removeClass("pp1");setsize()}
$("#screencontrol").addClass("col-xl-10").removeClass("col-md-12").removeClass("col-xl-12");$("#sp").removeClass("col-sm-12 col-md-11 col-lg-6 col-xl-5").removeClass("col-lg-8");$("#sp2").appendTo("#sp").removeClass("col-lg-8");$("#mvlist").addClass("col-lg-3").removeClass("col-lg-4");$("#mvlist").appendTo("#screencontainer");videoPlayer.resizeAll();$(".pcmode").addClass("active");$(".mvmode, .tvmode").removeClass("active")}else if($("body").hasClass("playmode1")){$("#mvCarousel").slick("refresh");var screenwidth=$(window).width();if(isMobile.any()&&window.innerHeight>window.innerWidth){$("#programlist").addClass("is-mobile").removeClass("is-tablet");$("#tvprograms").removeClass("d-none");$("#tvprograms .epg-content.nano").nanoScroller({scrollTo:$(".epg-item.active")});$("#tvprograms .epg-header .selector .dropdown-menu").nanoScroller({scrollTo:$(".dropdown-item.active")})}else{$("#superadv").addClass("pp1");setsize();$("#programlist").addClass("is-tablet").removeClass("is-mobile");$("#tvprograms").addClass("d-none")}
$("#screencontrol").addClass("col-md-12").addClass("col-xl-12").removeClass("col-xl-10");$("#sp2").appendTo("#set2").removeClass("col-lg-8");$("#sp").addClass("col-sm-12 col-md-11 col-lg-6 col-xl-5").removeClass("col-lg-8");if(!videoPlayer.stretching){videoPlayer.toggleStretch()}
videoPlayer.resizeAll();$(".tvmode").addClass("active");$(".pcmode, .mvmode").removeClass("active")}else if($("body").hasClass("playmode3")){$("#tvprograms").addClass("d-none");if(!isMobile.any()){$("#superadv").removeClass("pp1");setsize()}
$("#screencontrol").addClass("col-md-12").addClass("col-xl-12").removeClass("col-xl-10");$("#sp").addClass("col-sm-12").removeClass("col-lg-6 col-xl-5");$("#sp2").appendTo("#set2").addClass("col-lg-8");$("#mvlist").appendTo("#set2").addClass("col-lg-4").removeClass("col-lg-3");videoPlayer.resizeAll();$(".mvmode").addClass("active");$(".pcmode, .tvmode").removeClass("active")}}
function switchmode1(elem){$("body").addClass("playmode1").removeClass("playmode2").removeClass("playmode3");detectmode()}
function switchmode2(elem){$("body").addClass("playmode2").removeClass("playmode1").removeClass("playmode3");detectmode()}
function switchmode3(elem){$("body").addClass("playmode3").removeClass("playmode1").removeClass("playmode2");detectmode()}
function showinfo(){$(".mvinfo").toggleClass("d-none")}
function showdetail(){$(".expand-text").toggleClass("active");$(".mvdetail").toggleClass("d-none")}
function showcomment(){$("#commentwrap").toggleClass("d-none")}
$(window).on("orientationchange",function(){videoPlayer.resizeAll();if(tablet_device&&$("body").hasClass("playmode1")&&window.innerWidth>window.innerHeight&&$("html").hasClass("fullon")===!1){$("#tvprograms").removeClass("d-none");$("#programlist").addClass("is-mobile").removeClass("is-tablet").addClass("is-show");$("#program-btn").removeClass("active")}else if(tablet_device&&$("body").hasClass("playmode1")&&window.innerHeight>window.innerWidth&&$("html").hasClass("fullon")===!1){$("#tvprograms").addClass("d-none");$("#programlist").addClass("is-tablet").removeClass("is-mobile").removeClass("is-show")}});$(document).ready(function(){if(isMobile.any()){$("#demo-non-form").mobiscroll().select({theme:"ios",display:"bottom",lang:"zh",minWidth:200,inputClass:"demo-non-form"});$(".demo-container .icon-expand_more").click(function(){　
$("#demo-non-form").trigger("click")})
$("#mobi-non-form").mobiscroll().select({theme:"ios",display:"bottom",lang:"zh",minWidth:200,inputClass:"mobi-non-form"});$(".mobi-container .icon-expand_more").click(function(){　
$("#mobi-non-form").trigger("click")})
var w=$("#mcontrol_content").width();$("#mcontrol_tab").click(function(){if($("#mcontrol").css("right")=="-"+w+"px"){$("#mcontrol").animate({right:"0px"},600,"swing")}else{$("#mcontrol").animate({right:"-"+w+"px"},600,"swing")}});$("#mcontrol_content").click(function(){　
$("#mcontrol").animate({right:"-"+w+"px"},600,"swing")})}
if(!isMobile.any()||tablet_device){setsize()}
$("#elite_vp_fsBtn").click(function(){$("html").toggleClass("fullon");scrollTop=getScrollTop();if($("html").hasClass("fullon")){$("body").css("top",-scrollTop)}else{to(scrollTop)}
$("body").toggleClass("dialog-open");$(".navbar").toggleClass("d-none")});$("#taoplayer, .playmode1 .topttl").hover(function(){$(".player-ui").removeClass("fade");$(".topttl").addClass("fadein");$(".gradient-bottom").addClass("fadein");setTimeout(function(){$(".player-ui").addClass("fade");$(".topttl").removeClass("fadein");$(".gradient-bottom").removeClass("fadein")},8000);event.stopPropagation()});$("#pagem iframe").hover(function(){$(".player-ui").removeClass("fade");$(".gradient-bottom, .topttl").addClass("fadein");$("#supercontrol").addClass("d-md-block");setTimeout(function(){$(".player-ui").addClass("fade");$(".gradient-bottom, .topttl").removeClass("fadein");$("#supercontrol").removeClass("d-md-block")},3500)});$("#superadv .icon-close").click(function(){$("#superadv").addClass("d-none");event.stopPropagation()});$(".navTopTxt").focus(function(){$("#mtop .form-inline").addClass("active")});$(".btn").click(function(){$(this).toggleClass("active")});$(".likebtn").click(function(){$(".unlikebtn").removeClass("active")});$(".unlikebtn").click(function(){$(".likebtn").removeClass("active")});if($("#subscribe").hasClass("active")){$("#inform").removeClass("d-none")}else{$("#inform").addClass("d-none")}
$(".replybox>textarea").each(function(){imputempty(this)});$(".replybox>textarea").focus(function(){$(this).parent().find("button").removeClass("d-none")});$(".replybox>textarea").keyup(function(){imputempty(this)});$(".replybox .cancel").click(function(){$(".replybox textarea").val('');$(this).parent().find("button").addClass("d-none")});$("#mvcomments #contents .comments .replybox .cancel").click(function(){$(this).parent().addClass("d-none")});$("#programlist .dropdown-toggle").hover(function(){$("#programlist .dropdown-menu").css("opacity","1")});var swidth=$(window).width();var mcref;if(isMobile.any()&&swidth<769){mcref="true"}else{mcref="false"}
$("#mvCarousel").slick({mobileFirst:!0,dots:!1,infinite:mcref,speed:10,slidesToShow:9,slidesToScroll:3,responsive:[{breakpoint:1440,settings:{slidesToShow:9,slidesToScroll:3,}},{breakpoint:1281,settings:{slidesToShow:7,slidesToScroll:2,}},{breakpoint:1023,settings:{slidesToShow:5,slidesToScroll:5,}},{breakpoint:767,settings:{slidesToShow:5,slidesToScroll:5,}},{breakpoint:413,settings:{slidesToShow:4,slidesToScroll:4,}},{breakpoint:374,settings:{slidesToShow:3,slidesToScroll:3,}},{breakpoint:319,settings:{slidesToShow:3,slidesToScroll:3,}}]});$(".slick-slide").click(function(){$(this).addClass("playing").siblings(".slick-slide").removeClass("playing")});$("#nextpc").click(function(){var e=$(".slick-slide.playing");var n=e.next(".slick-slide");var m=$(".slick-slide:first-child");if(e.is(":last-child")){$("#mvCarousel").slick("slickPrev");m.addClass("playing").siblings(".slick-slide").removeClass("playing")}else{if(!n.hasClass("slick-active")){$("#mvCarousel").slick("slickNext")}
n.addClass("playing").siblings(".slick-slide").removeClass("playing")}});$("#prevpc").click(function(){var e=$(".slick-slide.playing");var n=e.prev(".slick-slide");var m=$(".slick-slide:last-child");if(e.is(":first-child")){$("#mvCarousel").slick("slickNext");m.addClass("playing").siblings(".slick-slide").removeClass("playing")}else{if(!n.hasClass("slick-active")){$("#mvCarousel").slick("slickPrev")}
n.addClass("playing").siblings(".slick-slide").removeClass("playing")}})})