!function(d){function m(e,c){var l=e[k];l=l&&a[l];if(void 0===c)return l||f(e);if(l){if(c in l)return l[c];var n=h(c);if(n in l)return l[n]}return b.call(d(e),c)}function f(e,b,l){var n=e[k]||(e[k]=++d.uuid);e=a[n]||(a[n]=c(e));return void 0!==b&&(e[h(b)]=l),e}function c(a){var e={};return d.each(a.attributes||g,function(a,b){0==b.name.indexOf("data-")&&(e[h(b.name.replace("data-",""))]=d.zepto.deserializeValue(b.value))}),e}var a={},b=d.fn.data,h=d.camelCase,k=d.expando="Zepto"+ +new Date,g=[];d.fn.data=
function(a,b){return void 0===b?d.isPlainObject(a)?this.each(function(e,b){d.each(a,function(a,e){f(b,a,e)})}):0 in this?m(this[0],a):void 0:this.each(function(){f(this,a,b)})};d.fn.removeData=function(e){return"string"==typeof e&&(e=e.split(/\s+/)),this.each(function(){var b=this[k],c=b&&a[b];c&&d.each(e||c,function(a){delete c[e?h(this):a]})})};["remove","empty"].forEach(function(a){var e=d.fn[a];d.fn[a]=function(){var b=this.find("*");return"remove"===a&&(b=b.add(this)),b.removeData(),e.call(this)}})}(window.Zepto);
!function(d){var m={};d.tpl=function(d,c,a){var b=/[^\w\-\.:]/.test(d)?function(a,d){var c,e=[],h=[];for(c in a)e.push(c),h.push(a[c]);return(new Function(e,b.code)).apply(d||a,h)}:m[d]=m[d]||this.get(document.getElementById(d).innerHTML);return b.code=b.code||"var $parts=[]; $parts.push('"+d.replace(/\\/g,"\\\\").replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/(^|%>)[^\t]*/g,function(a){return a.replace(/'/g,"\\'")}).replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("$parts.push('")+
"'); return $parts.join('');",c?b(c,a):b};d.adaptObject=function(f,c,a,b,h,k){if("string"!=typeof a){var g=d.extend({},c,"object"==typeof a&&a),e=!1;d.isArray(f)&&f.length&&"script"==d(f)[0].nodeName.toLowerCase()?(f=d(d.tpl(f[0].innerHTML,g)).appendTo("body"),e=!0):d.isArray(f)&&f.length&&""==f.selector?(f=d(d.tpl(f[0].outerHTML,g)).appendTo("body"),e=!0):d.isArray(f)||(f=d(d.tpl(b,g)).appendTo("body"),e=!0)}return f.each(function(){var b=d(this),l=b.data("fz."+k);l||b.data("fz."+k,l=new h(this,
d.extend({},c,"object"==typeof a&&a),e));"string"==typeof a&&l[a]()})}}(window.Zepto);
!function(d){function m(){return!1}var f={title:"",content:"",button:["\u786e\u8ba4"],select:0,allowScroll:!1,callback:function(){}},c=function(a,b,c){this.option=d.extend(f,b);this.element=d(a);this._isFromTpl=c;this.button=d(a).find('[data-role="button"]');this._bindEvent();this.toggle()};c.prototype={_bindEvent:function(){var a=this;a.button.on("tap",function(){var b=d(a.button).index(d(this)),c=d.Event("dialog:action");c.index=b;a.element.trigger(c);a.hide.apply(a)})},toggle:function(){this.element.hasClass("show")?
this.hide():this.show()},show:function(){this.element.trigger(d.Event("dialog:show"));this.element.addClass("show");this.option.allowScroll&&this.element.on("touchmove",m)},hide:function(){this.element.trigger(d.Event("dialog:hide"));this.element.removeClass("show");this.element.off("touchmove",m);this._isFromTpl&&this.element.remove()}};d.fn.dialog=d.dialog=function(a){return d.adaptObject(this,f,a,'<div class="ui-dialog"><div class="ui-dialog-cnt"><div class="ui-dialog-bd"><div><h4><%=title%></h4><div><%=content%></div></div></div><div class="ui-dialog-ft ui-btn-group"><% for (var i = 0; i < button.length; i++) { %><% if (i == select) { %><button type="button" data-role="button"  class="select" id="dialogButton<%=i%>"><%=button[i]%></button><% } else { %><button type="button" data-role="button" id="dialogButton<%=i%>"><%=button[i]%></div><% } %><% } %></div></div></div>',
c,"dialog")}}(window.Zepto);
!function(d){var m={content:"\u52a0\u8f7d\u4e2d..."},f=function(c,a,b){this.element=d(c);this._isFromTpl=b;this.option=d.extend(m,a);this.show()};f.prototype={show:function(){var c=d.Event("loading:show");this.element.trigger(c);this.element.show()},hide:function(){var c=d.Event("loading:hide");this.element.trigger(c);this.element.remove()}};d.fn.loading=d.loading=function(c){return d.adaptObject(this,m,c,'<div class="ui-loading-block show"><div class="ui-loading-cnt"><i class="ui-loading-bright"></i><p><%=content%></p></div></div>',f,
"loading")}}(window.Zepto);
(function(d){function m(a,b){this.wrapper="string"==typeof a?d(a)[0]:a;this.options={startX:0,startY:0,scrollY:!0,scrollX:!1,directionLockThreshold:5,momentum:!0,duration:300,bounce:!0,bounceTime:600,bounceEasing:"",preventDefault:!0,eventPassthrough:!0,freeScroll:!1,bindToWrapper:!0,resizePolling:60,disableMouse:!1,disableTouch:!1,disablePointer:!1,tap:!0,click:!1,preventDefaultException:{tagName:/^(INPUT|TEXTAREA|BUTTON|SELECT)$/},HWCompositing:!0,useTransition:!0,useTransform:!0};for(var h in b)this.options[h]=
b[h];if(this.options.role||!1!==this.options.scrollX||(this.options.eventPassthrough="horizontal"),"slider"===this.options.role){if(this.options.scrollX=!0,this.options.scrollY=!1,this.options.momentum=!1,this.scroller=d(".ui-slider-content",this.wrapper)[0],d(this.scroller.children[0]).addClass("current"),this.currentPage=0,this.count=this.scroller.children.length,this.scroller.style.width=this.count+"00%",this.itemWidth=this.scroller.children[0].clientWidth,this.scrollWidth=this.itemWidth*this.count,
this.options.indicator){var k='<ul class="ui-slider-indicators">';for(h=1;h<=this.count;h++)k+=1===h?'<li class="current">'+h+"</li>":"<li>"+h+"</li>";k+="</ul>";d(this.wrapper).append(k);this.indicator=d(".ui-slider-indicators",this.wrapper)[0]}}else"tab"===this.options.role?(this.options.scrollX=!0,this.options.scrollY=!1,this.options.momentum=!1,this.scroller=d(".ui-tab-content",this.wrapper)[0],this.nav=d(".ui-tab-nav",this.wrapper)[0],d(this.scroller.children[0]).addClass("current"),d(this.nav.children[0]).addClass("current"),
this.currentPage=0,this.count=this.scroller.children.length,this.scroller.style.width=this.count+"00%",this.itemWidth=this.scroller.children[0].clientWidth,this.scrollWidth=this.itemWidth*this.count):this.scroller=this.wrapper.children[0];if(this.scrollerStyle=this.scroller.style,this.translateZ=c.hasPerspective&&this.options.HWCompositing?" translateZ(0)":"",this.options.useTransition=c.hasTransition&&this.options.useTransition,this.options.useTransform=c.hasTransform&&this.options.useTransform,
this.options.eventPassthrough=!0===this.options.eventPassthrough?"vertical":this.options.eventPassthrough,this.options.preventDefault=!this.options.eventPassthrough&&this.options.preventDefault,this.options.scrollX="horizontal"!=this.options.eventPassthrough&&this.options.scrollX,this.options.scrollY="vertical"!=this.options.eventPassthrough&&this.options.scrollY,this.options.freeScroll=this.options.freeScroll&&!this.options.eventPassthrough,this.options.directionLockThreshold=this.options.eventPassthrough?
0:this.options.directionLockThreshold,this.options.bounceEasing="string"==typeof this.options.bounceEasing?c.ease[this.options.bounceEasing]||c.ease.circular:this.options.bounceEasing,this.options.resizePolling=void 0===this.options.resizePolling?60:this.options.resizePolling,!0===this.options.tap&&(this.options.tap="tap"),!1===this.options.useTransform&&(this.scroller.style.position="relative"),this.x=0,this.y=0,this.directionX=0,this.directionY=0,this._events={},this._init(),this.refresh(),this.scrollTo(this.options.startX,
this.options.startY),this.enable(),this.options.autoplay){var g=this;this.options.interval=this.options.interval||2E3;this.options.flag=setTimeout(function(){g._autoplay.apply(g)},g.options.interval)}}var f=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)},c=function(){function a(a){return!1!==c&&(""===c?a:c+a.charAt(0).toUpperCase()+a.substr(1))}
var b={},d=document.createElement("div").style,c=function(){for(var a,b=["t","webkitT","MozT","msT","OT"],c=0,h=b.length;c<h;c++)if(a=b[c]+"ransform",a in d)return b[c].substr(0,b[c].length-1);return!1}();b.getTime=Date.now||function(){return(new Date).getTime()};b.extend=function(a,b){for(var e in b)a[e]=b[e]};b.addEvent=function(a,b,c,d){a.addEventListener(b,c,!!d)};b.removeEvent=function(a,b,c,d){a.removeEventListener(b,c,!!d)};b.prefixPointerEvent=function(a){return window.MSPointerEvent?"MSPointer"+
a.charAt(9).toUpperCase()+a.substr(10):a};b.momentum=function(a,b,c,d,h,g){var e,l;b=a-b;c=Math.abs(b)/c;return g=void 0===g?6E-4:g,e=a+c*c/(2*g)*(0>b?-1:1),l=c/g,e<d?(e=h?d-h/2.5*(c/8):d,b=Math.abs(e-a),l=b/c):0<e&&(e=h?h/2.5*(c/8):0,b=Math.abs(a)+e,l=b/c),{destination:Math.round(e),duration:l}};var g=a("transform");return b.extend(b,{hasTransform:!1!==g,hasPerspective:a("perspective")in d,hasTouch:"ontouchstart"in window,hasPointer:window.PointerEvent||window.MSPointerEvent,hasTransition:a("transition")in
d}),b.isBadAndroid=/Android /.test(window.navigator.appVersion)&&!/Chrome\/\d/.test(window.navigator.appVersion),b.extend(b.style={},{transform:g,transitionTimingFunction:a("transitionTimingFunction"),transitionDuration:a("transitionDuration"),transitionDelay:a("transitionDelay"),transformOrigin:a("transformOrigin"),transitionProperty:a("transitionProperty")}),b.offset=function(a){for(var b=-a.offsetLeft,e=-a.offsetTop;a=a.offsetParent;)b-=a.offsetLeft,e-=a.offsetTop;return{left:b,top:e}},b.preventDefaultException=
function(a,b){for(var e in b)if(b[e].test(a[e]))return!0;return!1},b.extend(b.eventType={},{touchstart:1,touchmove:1,touchend:1,mousedown:2,mousemove:2,mouseup:2,pointerdown:3,pointermove:3,pointerup:3,MSPointerDown:3,MSPointerMove:3,MSPointerUp:3}),b.extend(b.ease={},{quadratic:{style:"cubic-bezier(0.25, 0.46, 0.45, 0.94)",fn:function(a){return a*(2-a)}},circular:{style:"cubic-bezier(0.1, 0.57, 0.1, 1)",fn:function(a){return Math.sqrt(1- --a*a)}},back:{style:"cubic-bezier(0.175, 0.885, 0.32, 1.275)",
fn:function(a){return--a*a*(5*a+4)+1}},bounce:{style:"",fn:function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375}},elastic:{style:"",fn:function(a){return 0===a?0:1==a?1:.4*Math.pow(2,-10*a)*Math.sin(2*(a-.055)*Math.PI/.22)+1}}}),b.tap=function(a,b){var c=document.createEvent("Event");c.initEvent(b,!0,!0);c.pageX=a.pageX;c.pageY=a.pageY;a.target.dispatchEvent(c)},b.click=function(a){var b,c=a.target;
/(SELECT|INPUT|TEXTAREA)/i.test(c.tagName)||(b=document.createEvent("MouseEvents"),b.initMouseEvent("click",!0,!0,a.view,1,c.screenX,c.screenY,c.clientX,c.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,null),b._constructed=!0,c.dispatchEvent(b))},b}();m.prototype={_init:function(){this._initEvents()},_initEvents:function(a){a=a?c.removeEvent:c.addEvent;var b=this.options.bindToWrapper?this.wrapper:window;a(window,"orientationchange",this);a(window,"resize",this);this.options.click&&a(this.wrapper,
"click",this,!0);this.options.disableMouse||(a(this.wrapper,"mousedown",this),a(b,"mousemove",this),a(b,"mousecancel",this),a(b,"mouseup",this));c.hasPointer&&!this.options.disablePointer&&(a(this.wrapper,c.prefixPointerEvent("pointerdown"),this),a(b,c.prefixPointerEvent("pointermove"),this),a(b,c.prefixPointerEvent("pointercancel"),this),a(b,c.prefixPointerEvent("pointerup"),this));c.hasTouch&&!this.options.disableTouch&&(a(this.wrapper,"touchstart",this),a(b,"touchmove",this),a(b,"touchcancel",
this),a(b,"touchend",this));a(this.scroller,"transitionend",this);a(this.scroller,"webkitTransitionEnd",this);a(this.scroller,"oTransitionEnd",this);a(this.scroller,"MSTransitionEnd",this);"tab"===this.options.role&&(a(this.nav,"touchend",this),a(this.nav,"mouseup",this),a(this.nav,"pointerup",this))},refresh:function(){this.wrapper.offsetHeight;this.wrapperWidth=this.wrapper.clientWidth;this.wrapperHeight=this.wrapper.clientHeight;var a=window.getComputedStyle(this.wrapper,null),b=a["padding-top"].replace(/[^-\d.]/g,
""),d=a["padding-bottom"].replace(/[^-\d.]/g,""),k=a["padding-left"].replace(/[^-\d.]/g,"");a=a["padding-right"].replace(/[^-\d.]/g,"");var g=window.getComputedStyle(this.scroller,null),e=g["margin-top"].replace(/[^-\d.]/g,""),f=g["margin-bottom"].replace(/[^-\d.]/g,""),l=g["margin-left"].replace(/[^-\d.]/g,"");g=g["margin-right"].replace(/[^-\d.]/g,"");this.scrollerWidth=this.scroller.offsetWidth+parseInt(k)+parseInt(a)+parseInt(l)+parseInt(g);this.scrollerHeight=this.scroller.offsetHeight+parseInt(b)+
parseInt(d)+parseInt(e)+parseInt(f);"slider"!==this.options.role&&"tab"!==this.options.role||(this.itemWidth=this.scroller.children[0].clientWidth,this.scrollWidth=this.itemWidth*this.count,this.scrollerWidth=this.scrollWidth);this.maxScrollX=this.wrapperWidth-this.scrollerWidth;this.maxScrollY=this.wrapperHeight-this.scrollerHeight;this.hasHorizontalScroll=this.options.scrollX&&0>this.maxScrollX;this.hasVerticalScroll=this.options.scrollY&&0>this.maxScrollY;this.hasHorizontalScroll||(this.maxScrollX=
0,this.scrollerWidth=this.wrapperWidth);this.hasVerticalScroll||(this.maxScrollY=0,this.scrollerHeight=this.wrapperHeight);this.directionY=this.directionX=this.endTime=0;this.wrapperOffset=c.offset(this.wrapper);this.resetPosition()},handleEvent:function(a){switch(a.type){case "touchstart":case "pointerdown":case "MSPointerDown":case "mousedown":this._start(a);break;case "touchmove":case "pointermove":case "MSPointerMove":case "mousemove":this._move(a);break;case "touchend":case "pointerup":case "MSPointerUp":case "mouseup":case "touchcancel":case "pointercancel":case "MSPointerCancel":case "mousecancel":this._end(a);
break;case "orientationchange":case "resize":this._resize();break;case "transitionend":case "webkitTransitionEnd":case "oTransitionEnd":case "MSTransitionEnd":this._transitionEnd(a);break;case "wheel":case "DOMMouseScroll":case "mousewheel":this._wheel(a);break;case "keydown":this._key(a);break;case "click":a._constructed||(a.preventDefault(),a.stopPropagation())}},_start:function(a){if(!(1!=c.eventType[a.type]&&0!==a.button||!this.enabled||this.initiated&&c.eventType[a.type]!==this.initiated)){!this.options.preventDefault||
c.isBadAndroid||c.preventDefaultException(a.target,this.options.preventDefaultException)||a.preventDefault();var b,d=a.touches?a.touches[0]:a;if(this.initiated=c.eventType[a.type],this.moved=!1,this.distX=0,this.distY=0,this.directionX=0,this.directionY=0,this.directionLocked=0,this._transitionTime(),this.startTime=c.getTime(),this.options.useTransition&&this.isInTransition&&"slider"!==this.options.role&&"tab"!==this.options.role?(this.isInTransition=!1,b=this.getComputedPosition(),this._translate(Math.round(b.x),
Math.round(b.y))):!this.options.useTransition&&this.isAnimating&&(this.isAnimating=!1),this.startX=this.x,this.startY=this.y,this.absStartX=this.x,this.absStartY=this.y,this.pointX=d.pageX,this.pointY=d.pageY,this.options.autoplay){var k=this;clearTimeout(this.options.flag);this.options.flag=setTimeout(function(){k._autoplay.apply(k)},k.options.interval)}event.stopPropagation()}},_move:function(a){if(this.enabled&&c.eventType[a.type]===this.initiated){this.options.preventDefault&&a.preventDefault();
var b,h,k=a.touches?a.touches[0]:a,g=k.pageX-this.pointX,e=k.pageY-this.pointY,f=c.getTime();if(this.pointX=k.pageX,this.pointY=k.pageY,this.distX+=g,this.distY+=e,b=Math.abs(this.distX),h=Math.abs(this.distY),!(300<f-this.endTime&&10>b&&10>h)){if(this.directionLocked||this.options.freeScroll||(b>h+this.options.directionLockThreshold?this.directionLocked="h":h>=b+this.options.directionLockThreshold?this.directionLocked="v":this.directionLocked="n"),"h"==this.directionLocked){if("tab"===this.options.role&&
d(this.scroller).children("li").height("auto"),"vertical"==this.options.eventPassthrough)a.preventDefault();else if("horizontal"==this.options.eventPassthrough)return void(this.initiated=!1);e=0}else if("v"==this.directionLocked){if("horizontal"==this.options.eventPassthrough)a.preventDefault();else if("vertical"==this.options.eventPassthrough)return void(this.initiated=!1);g=0}g=this.hasHorizontalScroll?g:0;e=this.hasVerticalScroll?e:0;a=this.x+g;b=this.y+e;(0<a||a<this.maxScrollX)&&(a=this.options.bounce?
this.x+g/3:0<a?0:this.maxScrollX);(0<b||b<this.maxScrollY)&&(b=this.options.bounce?this.y+e/3:0<b?0:this.maxScrollY);this.directionX=0<g?-1:0>g?1:0;this.directionY=0<e?-1:0>e?1:0;this.moved=!0;this._translate(a,b);300<f-this.startTime&&(this.startTime=f,this.startX=this.x,this.startY=this.y)}}},_end:function(a){if(this.enabled&&c.eventType[a.type]===this.initiated){this.options.preventDefault&&!c.preventDefaultException(a.target,this.options.preventDefaultException)&&a.preventDefault();var b,h,k=
(a.changedTouches?a.changedTouches[0]:a,c.getTime()-this.startTime),g=Math.round(this.x),e=Math.round(this.y),f=Math.abs(g-this.startX),l=(Math.abs(e-this.startY),0),m="";if(this.isInTransition=0,this.initiated=0,this.endTime=c.getTime(),this.resetPosition(this.options.bounceTime))return void("tab"===this.options.role&&d(this.scroller.children[this.currentPage]).siblings("li").height(0));if(this.scrollTo(g,e),this.moved||(this.options.tap&&1===c.eventType[a.type]&&c.tap(a,this.options.tap),this.options.click&&
c.click(a)),this.options.momentum&&300>k&&(b=this.hasHorizontalScroll?c.momentum(this.x,this.startX,k,this.maxScrollX,this.options.bounce?this.wrapperWidth:0,this.options.deceleration):{destination:g,duration:0},h=this.hasVerticalScroll?c.momentum(this.y,this.startY,k,this.maxScrollY,this.options.bounce?this.wrapperHeight:0,this.options.deceleration):{destination:e,duration:0},g=b.destination,e=h.destination,l=Math.max(b.duration,h.duration),this.isInTransition=1),g!=this.x||e!=this.y)return(0<g||
g<this.maxScrollX||0<e||e<this.maxScrollY)&&(m=c.ease.quadratic),void this.scrollTo(g,e,l,m);"tab"===this.options.role&&d(event.target).closest("ul").hasClass("ui-tab-nav")&&(d(this.nav).children().removeClass("current"),d(event.target).addClass("current"),a=this.currentPage,this.currentPage=d(event.target).index(),d(this.scroller).children().height("auto"),this._execEvent("beforeScrollStart",a,this.currentPage));"slider"!==this.options.role&&"tab"!==this.options.role||(30>f?this.scrollTo(-this.itemWidth*
this.currentPage,0,this.options.bounceTime,this.options.bounceEasing):0>g-this.startX?(this._execEvent("beforeScrollStart",this.currentPage,this.currentPage+1),this.scrollTo(-this.itemWidth*++this.currentPage,0,this.options.bounceTime,this.options.bounceEasing)):0<=g-this.startX&&(this._execEvent("beforeScrollStart",this.currentPage,this.currentPage-1),this.scrollTo(-this.itemWidth*--this.currentPage,0,this.options.bounceTime,this.options.bounceEasing)),"tab"===this.options.role&&d(this.scroller.children[this.currentPage]).siblings("li").height(0),
this.indicator&&30<=f?(d(this.indicator).children().removeClass("current"),d(this.indicator.children[this.currentPage]).addClass("current")):this.nav&&30<=f&&(d(this.nav).children().removeClass("current"),d(this.nav.children[this.currentPage]).addClass("current")),d(this.scroller).children().removeClass("current"),d(this.scroller.children[this.currentPage]).addClass("current"))}},_resize:function(){var a=this;clearTimeout(this.resizeTimeout);this.resizeTimeout=setTimeout(function(){a.refresh()},this.options.resizePolling)},
_transitionEnd:function(a){a.target==this.scroller&&this.isInTransition&&(this._transitionTime(),this.resetPosition(this.options.bounceTime)||(this.isInTransition=!1,this._execEvent("scrollEnd",this.currentPage)))},destroy:function(){this._initEvents(!0)},resetPosition:function(a){var b=this.x,c=this.y;return a=a||0,!this.hasHorizontalScroll||0<this.x?b=0:this.x<this.maxScrollX&&(b=this.maxScrollX),!this.hasVerticalScroll||0<this.y?c=0:this.y<this.maxScrollY&&(c=this.maxScrollY),(b!=this.x||c!=this.y)&&
(this.scrollTo(b,c,a,this.options.bounceEasing),!0)},disable:function(){this.enabled=!1},enable:function(){this.enabled=!0},on:function(a,b){this._events[a]||(this._events[a]=[]);this._events[a].push(b)},off:function(a,b){if(this._events[a]){var c=this._events[a].indexOf(b);-1<c&&this._events[a].splice(c,1)}},_execEvent:function(a){if(this._events[a]){var b=0,c=this._events[a].length;if(c)for(;b<c;b++)this._events[a][b].apply(this,[].slice.call(arguments,1))}},scrollTo:function(a,b,d,f){f=f||c.ease.circular;
this.isInTransition=this.options.useTransition&&0<d;!d||this.options.useTransition&&f.style?("slider"!==this.options.role&&"tab"!==this.options.role||(d=this.options.duration,this.scrollerStyle[c.style.transitionProperty]=c.style.transform),this.scrollerStyle[c.style.transitionTimingFunction]=f.style,this._transitionTime(d),this._translate(a,b)):this._animate(a,b,d,f.fn)},scrollToElement:function(a,b,d,f,g){if(a=a.nodeType?a:this.scroller.querySelector(a)){var e=c.offset(a);e.left-=this.wrapperOffset.left;
e.top-=this.wrapperOffset.top;!0===d&&(d=Math.round(a.offsetWidth/2-this.wrapper.offsetWidth/2));!0===f&&(f=Math.round(a.offsetHeight/2-this.wrapper.offsetHeight/2));e.left-=d||0;e.top-=f||0;e.left=0<e.left?0:e.left<this.maxScrollX?this.maxScrollX:e.left;e.top=0<e.top?0:e.top<this.maxScrollY?this.maxScrollY:e.top;b=void 0===b||null===b||"auto"===b?Math.max(Math.abs(this.x-e.left),Math.abs(this.y-e.top)):b;this.scrollTo(e.left,e.top,b,g)}},_transitionTime:function(a){a=a||0;this.scrollerStyle[c.style.transitionDuration]=
a+"ms";!a&&c.isBadAndroid&&(this.scrollerStyle[c.style.transitionDuration]="0.001s")},_translate:function(a,b){this.options.useTransform?this.scrollerStyle[c.style.transform]="translate("+a+"px,"+b+"px)"+this.translateZ:(a=Math.round(a),b=Math.round(b),this.scrollerStyle.left=a+"px",this.scrollerStyle.top=b+"px");this.x=a;this.y=b},getComputedPosition:function(){var a,b,d=window.getComputedStyle(this.scroller,null);return this.options.useTransform?(d=d[c.style.transform].split(")")[0].split(", "),
a=+(d[12]||d[4]),b=+(d[13]||d[5])):(a=+d.left.replace(/[^-\d.]/g,""),b=+d.top.replace(/[^-\d.]/g,"")),{x:a,y:b}},_animate:function(a,b,d,k){function g(){var n,r,q,p=c.getTime();return p>=t?(e.isAnimating=!1,e._translate(a,b),void(e.resetPosition(e.options.bounceTime)||e._execEvent("scrollEnd",this.currentPage))):(p=(p-m)/d,q=k(p),n=(a-h)*q+h,r=(b-l)*q+l,e._translate(n,r),void(e.isAnimating&&f(g)))}var e=this,h=this.x,l=this.y,m=c.getTime(),t=m+d;this.isAnimating=!0;g()},_autoplay:function(){var a=
this,b=a.currentPage;a.currentPage=a.currentPage>=a.count-1?0:++a.currentPage;a._execEvent("beforeScrollStart",b,a.currentPage);"tab"===this.options.role&&(d(this.scroller).children().height("auto"),document.body.scrollTop=0);a.scrollTo(-a.itemWidth*a.currentPage,0,a.options.bounceTime,a.options.bounceEasing);a.indicator?(d(a.indicator).children().removeClass("current"),d(a.indicator.children[a.currentPage]).addClass("current"),d(a.scroller).children().removeClass("current"),d(a.scroller.children[a.currentPage]).addClass("current")):
a.nav&&(d(a.nav).children().removeClass("current"),d(a.nav.children[a.currentPage]).addClass("current"),d(a.scroller).children().removeClass("current"),d(a.scroller.children[a.currentPage]).addClass("current"));a.options.flag=setTimeout(function(){a._autoplay.apply(a)},a.options.interval)}};window.fz=window.fz||{};window.frozen=window.frozen||{};window.fz.Scroll=window.frozen.Scroll=m;"function"==typeof define&&define(function(a,b,c){c.exports=m})})(window.Zepto);
!function(d){var m={content:"",stayTime:1E3,type:"info",callback:function(){}},f=function(c,a,b){var f=this;this.element=d(c);this._isFromTpl=b;this.elementHeight=d(c).height();this.option=d.extend(m,a);d(c).css({"-webkit-transform":"translateY(-"+this.elementHeight+"px)"});setTimeout(function(){d(c).css({"-webkit-transition":"all .5s"});f.show()},20)};f.prototype={show:function(){var c=this;c.element.trigger(d.Event("tips:show"));this.element.css({"-webkit-transform":"translateY(0px)"});0<c.option.stayTime&&
setTimeout(function(){c.hide()},c.option.stayTime)},hide:function(){var c=this;c.element.trigger(d.Event("tips:hide"));this.element.css({"-webkit-transform":"translateY(-"+this.elementHeight+"px)"});setTimeout(function(){c._isFromTpl&&c.element.remove()},500)}};d.fn.tips=d.tips=function(c){return d.adaptObject(this,m,c,'<div class="ui-poptips ui-poptips-<%=type%>"><div class="ui-poptips-cnt"><i></i><%=content%></div></div>',f,"tips")}}(window.Zepto);