(function(){$.fn.glDatePicker=function(a){var q=this.data("glDatePicker");return q?!0===a?q:this:this.each(function(){return $(this).data("glDatePicker",new Q(this,a))})};$.fn.glDatePicker.defaults={cssName:"default",zIndex:1E3,borderSize:1,calendarOffset:{x:0,y:1},showAlways:!1,hideOnClick:!0,allowMonthSelect:!0,allowYearSelect:!0,todayDate:new Date,selectedDate:null,prevArrow:"\u00ab",nextArrow:"\u00bb",selectableDates:null,selectableDateRange:null,specialDates:null,selectableMonths:null,selectableYears:null,
selectableDOW:null,monthNames:null,dowNames:null,dowOffset:0,onClick:function(a,q,h,d){a.val(h.toLocaleDateString())},onHover:function(a,q,h,d){},onShow:function(a){a.show()},onHide:function(a){a.hide()},firstDate:null};var Q=function(){function a(a,h){var d=this;d.el=$(a);var b=d.el;d.options=$.extend(!0,{},$.fn.glDatePicker.defaults,h);var c=d.options;d.calendar=$($.find("[gldp-el="+b.attr("gldp-id")+" ]"));c.selectedDate=c.selectedDate||c.todayDate;c.firstDate=(new Date(c.firstDate||c.selectedDate))._first();
(b.attr("gldp-id")||"").length||b.attr("gldp-id","gldp-"+Math.round(1E10*Math.random()));b.addClass("gldp-el").bind("click",function(b){d.show(b)}).bind("focus",function(b){d.show(b)});d.calendar.length&&!c.showAlways&&d.calendar.hide();$(document).bind("mouseup",function(a){a=a.target;var c=d.calendar;b.is(a)||c.is(a)||0!==c.has(a).length||!c.is(":visible")||d.hide()});d.render()}a.prototype={show:function(){$.each($(".gldp-el").not(this.el),function(a,h){if(h.length)h.options.onHide(h.calendar)});
this.options.onShow(this.calendar)},hide:function(){if(this.options&&!this.options.showAlways)this.options.onHide(this.calendar)},render:function(a){var h=this,d=h.el,b=h.options,c=h.calendar,l="gldp-"+b.cssName,v=b.todayDate._val(),w=v.time,k=b.borderSize+"px",A=function(b,K,a){for(var e=[],c=b;c<=K;c++)e.push(c);if(a){var d=[];$.each(a,function(e,a){a>=b&&a<=K&&0>d._indexOf(a)&&d.push(a)});e=d.length?d:e}e.sort();return e},q=A(0,11,b.selectableMonths),x=A(v.year-5,v.year+5,b.selectableYears);A=
A(0,6,b.selectableDOW);var B=b.dowNames||"\u65e5\u4e00\u4e8c\u4e09\u56db\u4e94\u516d".split("");v=b.monthNames||"1\u6708 2\u6708 3\u6708 4\u6708 5\u6708 6\u6708 7\u6708 8\u6708 9\u6708 10\u6708 11\u6708 12\u6708".split(" ");var g=d.outerWidth()+27,m=g/7+b.borderSize/7*6;g=g/8+b.borderSize/8*7;if(!c.length)h.calendar=c=$("<div/>").attr("gldp-el",d.attr("gldp-id")).data("is",!0).css({display:b.showAlways?void 0:"none",zIndex:b.zIndex,width:7*m+"px"}),$("body").append(c);else if(!eval(c.data("is"))){g=
c.outerWidth();var f=c.outerHeight();m=g/7+b.borderSize/7*6;g=f/8+b.borderSize/8*7}d.is(":visible")||c.hide();c.removeClass().addClass(l).children().remove();l=function(){var e=d.offset();c.css({top:e.top+d.outerHeight()+b.calendarOffset.y+"px",left:e.left+b.calendarOffset.x+"px"})};$(window).resize(l);l();l={width:m+"px",height:g+"px",lineHeight:g+"px"};g=function(e){var a=new Date(b.firstDate);for(e=e||0;;){a.setMonth(a.getMonth()+e);a.setDate(Math.min(1,a._max()));if(0==e)break;var d=a._val(),
c=d.year;if(-1!=q._indexOf(d.month))if(-1!=x._indexOf(c))break;else if(c<x[0]||c>x[x.length-1])return null}return a};var C=g(-1),D=g(1);g=b.firstDate=g();f=g._val();var J=f.month,L=f.year;g=new Date(g);f=Math.abs(Math.min(6,Math.max(0,b.dowOffset)));var n=g.getDay()-f;n=1>n?-7-n:-n;B=B.concat(B).slice(f,f+7);g._add(n);f=$("<div/>").addClass(" core border monyear ").css($.extend({},l,{borderWidth:k+" 0 0 "+k})).append($("<a/>").addClass("prev-arrow"+(C?"":"-off")).html(b.prevArrow)).mousedown(function(){return!1}).click(function(e){""!=
b.prevArrow&&C&&(e.stopPropagation(),C&&(b.firstDate=C,h.render()))});m=5*m-5*b.borderSize+b.borderSize;m=$("<div/>").addClass(" core border monyear title").css($.extend({},l,{width:m+"px",borderTopWidth:k,marginLeft:"-"+k}));n=$("<div/>").addClass(" core border monyear ").css($.extend({},l,{marginLeft:"-"+k,borderWidth:k+" "+k+" 0 0"})).append($("<a/>").addClass("next-arrow"+(D?"":"-off")).html(b.nextArrow)).mousedown(function(){return!1}).click(function(e){""!=b.nextArrow&&D&&(e.stopPropagation(),
D&&(b.firstDate=D,h.render()))});c.append(f).append(m).append(n);for(n=f=0;7>f;f++)for(var t=0;7>t;t++,n++){var E=new Date(g),r="day",F=b.zIndex+n,y=$("<div/>");if(f){E._add(t+7*(f-1));var p=E._val(),z=p.time,M=null,u=!0,G=function(b,a){!0===b.repeatYear&&a.setYear(p.year);!0===b.repeatMonth&&a.setMonth(p.month);return a._val()};y.html(p.date);b.selectableDateRange&&(u=!1,$.each(b.selectableDateRange,function(b,a){var e=a.from,c=a.to||null;c=c||new Date(a.from.getFullYear(),a.from.getMonth(),a.from._max());
e=G(a,e);c=G(a,c);if(z>=e.time&&z<=c.time)return u=!0}));if(b.selectableDates){if(b.selectableDateRange&&!u||u&&!b.selectableDateRange)u=!1;$.each(b.selectableDates,function(b,a){if(G(a,a.date).time==z)return u=!0})}!u||0>x._indexOf(p.year)||0>q._indexOf(p.month)||0>A._indexOf(p.day)?r="noday":(r="sun mon tue wed thu fri sat".split(" ")[p.day],J!=p.month&&(r+=" outday"),w==z&&(r="today",F+=50),b.selectedDate._time()==z&&(r="selected",F+=51),b.specialDates&&$.each(b.specialDates,function(b,a){G(a,
a.date).time==z&&(r=a.cssClass||"special",F+=52,M=a.data)}),y.mousedown(function(){return!1}).hover(function(a){a.stopPropagation();a=$(this).data("data");b.onHover(d,y,a.date,a.data)}).click(function(a){a.stopPropagation();a=$(this).data("data");b.selectedDate=b.firstDate=a.date;h.render(function(){!b.showAlways&&b.hideOnClick&&h.hide()});b.onClick(d,$(this),a.date,a.data)}))}else r="dow",y.html(B[t]),E=null;$.extend(l,{borderTopWidth:k,borderBottomWidth:k,borderLeftWidth:0<f||!f&&!t?k:0,borderRightWidth:0<
f||!f&&6==t?k:0,marginLeft:0<t?"-"+k:0,marginTop:0<f?"-"+k:0,zIndex:F});y.data("data",{date:E,data:M}).addClass(" core border "+r).css(l);c.append(y)}var P=function(a){b.allowMonthSelect&&(N.css({display:a?"inline-block":"none"}),H.css({display:a?"none":"inline-block"}));b.allowYearSelect&&(O.css({display:a?"none":"inline-block"}),I.css({display:a?"inline-block":"none"}))};w=function(){b.firstDate=new Date(I.val(),H.val(),1);h.render()};var H=$("<select/>").hide().change(w),I=$("<select/>").hide().change(w),
N=$("<span/>").html(v[J]).mousedown(function(){return!1}).click(function(a){a.stopPropagation();P(!1)}),O=$("<span/>").html(L).mousedown(function(){return!1}).click(function(a){a.stopPropagation();P(!0)});$.each(v,function(a,c){if(b.allowMonthSelect&&-1!=q._indexOf(a)){var d=$("<option/>").html(c).attr("value",a);a==J&&d.attr("selected","selected");H.append(d)}});$.each(x,function(a,c){if(b.allowYearSelect){var d=$("<option/>").html(c).attr("value",c);c==L&&d.attr("selected","selected");I.append(d)}});
w=$("<div/>").append(N).append(H).append(O).append(I);m.children().remove();m.append(w);(a||function(){})()}};return a}();(function(){Date.prototype._clear=function(){this.setHours(0);this.setMinutes(0);this.setSeconds(0);this.setMilliseconds(0);return this};Date.prototype._time=function(){return this._clear().getTime()};Date.prototype._max=function(){return[31,28+(1==(new Date(this.getYear(),1,29)).getMonth()?1:0),31,30,31,30,31,31,30,31,30,31][this.getMonth()]};Date.prototype._add=function(a){this.setDate(this.getDate()+
a)};Date.prototype._first=function(){var a=new Date(this);a.setDate(1);return a};Date.prototype._val=function(){this._clear();return{year:this.getFullYear(),month:this.getMonth(),date:this.getDate(),time:this.getTime(),day:this.getDay()}};Array.prototype._indexOf=function(a){return $.inArray(a,this)}})()})();